### ISSUE TITLE
API nutzen von anderen Servern aus

### ISSUE THREAD

**Issue by FreeSoccerHDX** [gruener-campus-malchow/GCMChat#3]
Failed to load http://sn0wman.pythonanywhere.com/api: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://freesoccerhdx.tk' is therefore not allowed access.

baldi hat glaube auch anfangs das problem gehabt, da fehlt glaube ich nur das, was dort auch oben steht...

**Comment by mojansch** [comment]
OK, ich gucke mal, wie man das ändert
